source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.5'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
# gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
# gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'bootsnap'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry-rails'  # rails console(もしくは、rails c)でirbの代わりにpryを使われる
  gem 'pry-doc'    # methodを表示
  gem 'pry-byebug' # デバッグを実施(Ruby 2.0以降で動作する)
  gem 'pry-stack_explorer' # スタックをたどれる

  # 静的解析
  gem 'rubocop', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

### env
gem 'dotenv-rails'

### view切り分け
gem 'jpmobile'

### ページ遷移のターボリンクス対応
gem 'jquery-turbolinks'

### ユーザーまわり
# gem 'devise'

### bootstrap
gem 'bootstrap-sass'
gem 'bootstrap-multiselect-rails'

### font-awesome
gem 'font-awesome-rails'

### 画像まわり
gem 'carrierwave'
# gem 'rmagick'

### ファイルのajax通信
gem 'remotipart', '~> 1.2'

### 検索
gem 'rails-i18n' # この行を追加(ransackには関係ないけどdate_select用)
gem 'ransack'

###ページネーション
gem 'kaminari'

### スクレイピング
gem 'mechanize'

### サイトマップ
gem 'sitemap_generator'

### annotate
gem 'annotate'

### パンくず
gem 'gretel'

### HTTPクライアント
gem 'httpclient'

### ハッシュ化 SHA-3
gem 'digest-sha3'

### YoutubeAPI
gem 'google-api-client', '0.8.6'

### エラー通知
gem 'exception_notification'
gem 'slack-notifier'

### セッションをDBに保存
gem 'activerecord-session_store'

gem 'therubyracer'